services:
  seed-by-speed:
    image: unraiders/seed-by-speed
    container_name: seed-by-speed
    environment:
      - TORRENT_CLIENT=qbittorrent|transmission # dejar el deseado
      - TORRENT_CLIENT_HOST=192.168.2.20
      - TORRENT_CLIENT_PORT=8090
      - TORRENT_CLIENT_USER=admin
      - TORRENT_CLIENT_PASSWORD=adminadmin
      - CRON_PAUSAR=*/30 * * * * # formato crontab
      - CRON_REANUDAR=0 7 * * * # formato crontab
      - DEBUG=1
    volumes:
      - /tu/ruta/local/seed-by-speed/:/app/data
    entrypoint: ./entrypoint.sh