services:
  seed-by-speed:
    image: unraiders/seed-by-speed
    container_name: seed-by-speed
    environment:
      - QBITTORRENT_HOST=192.168.1.100
      - QBITTORRENT_PORT=8080
      - QBITTORRENT_USER=admin
      - QBITTORRENT_PASSWORD=adminadmin
      - CRON_PAUSAR=*/30 * * * *
      - CRON_REANUDAR=0 7 * * *
      - DEBUG=1
    volumes:
      - /mnt/user/appdata/seed-by-speed/:/app/data
    entrypoint: ./entrypoint.sh